services:
  postgres:
    image: 'postgres:14-alpine'
    environment:
      - 'POSTGRES_DB=study_app'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5431:5432'
  rabbitmq:
    image: 'rabbitmq:latest'
    ports:
      - '5671:5672'
